package models

import (
    "time"

    "github.com/google/uuid"
    "gorm.io/gorm"
)

// AIAlert represents an alert generated by the AI engine for a transaction.
type AIAlert struct {
    ID             string    `json:"id" gorm:"primaryKey;type:char(36)"`
    TransactionID  string    `json:"transactionId" gorm:"type:char(36)"`
    AnomalyScore   float64   `json:"anomalyScore"`
    AlertMessage   string    `json:"alertMessage"`
    ResolvedStatus string    `json:"resolvedStatus" gorm:"default:'PENDING'"` // e.g., PENDING, RESOLVED
    CreatedAt      time.Time `json:"createdAt"`
    UpdatedAt      time.Time `json:"updatedAt"`
}

func (a *AIAlert) BeforeCreate(tx *gorm.DB) (err error) {
    a.ID = uuid.NewString()
    return
}
